on:
  push:
    branches:
      - master

name: 'Trigger: Push action'

jobs:
  shellcheck:
    name: Shellcheck
    runs-on: ubuntu-latest
    stage: linting
    image: registry.gitlab.com/pipeline-components/shellcheck:latest
    script:
      - |
        find . -name .git -type d -prune -o -type f -name \*.sh -print0 |
        xargs -0 -r -n1 shellcheck
